spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Bingoch/spring-cloud-config.git

server:
  port: 7005

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
